### ISSUE TITLE
runapp() won't work because of "Server.R" filename

### ISSUE THREAD

**Issue by homerhanumat** [rstudio-conf-2020/shiny-start-finish#2]
The Project 1 Build-UI app won't run on `runapp()` is because of the presence of a `server.R` file (case insensitive).  I guess R then assumes the presence of a `ui.R` or `www/index.html` file and complains when it doesn't find one, even though the ui is defined elsewhere.  Rename `Server.R` to `Knight_Bus.R` or whatever and it works.

**Comment by dtkaplan** [comment]
Thanks, Homer. I wouldn't have spotted the solution.

- Danny

**Comment by homerhanumat** [comment]
I don't believe that!  :)
